"""Initial migration

Revision ID: 777bfbc118ac
Revises: 
Create Date: 2025-06-22 19:47:44.718059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777bfbc118ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
